# Stack Overflow Developer's Dataset

In [50]:
import pandas as pd
import numpy as np

df = pd.read_csv('developer_dataset.csv', parse_dates=[1], index_col='RespondentID', na_values='', dtype={18:str, 19:str, 20:str})

In [10]:
df.head(30)

,Year,Country,Employment,UndergradMajor,DevType,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,Hobbyist,OrgSize,YearsCodePro,JobSeek,ConvertedComp,WorkWeekHrs,NEWJobHunt,NEWJobHuntResearch,NEWLearn
RespondentID,,,,,,,,,,,,,,,,,,,,
1,2018-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering",Engineering manager;Full-stack developer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141000.0,NaN,NaN,NaN,NaN
1,2019-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","Developer, full-stack",C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,No,100 to 499 employees,1.0,I am not interested in new job opportunities,61000.0,80.0,NaN,NaN,NaN
1,2020-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering",NaN,HTML/CSS;Ruby;SQL,Java;Ruby;Scala,MySQL;PostgreSQL;Redis;SQLite,MySQL;PostgreSQL,AWS;Docker;Linux;MacOS;Windows,Docker;Google Cloud Platform;Heroku;Linux;Windows,Yes,NaN,8.0,NaN,NaN,NaN,NaN,NaN,Once a year
2,2018-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering",Full-stack developer,C#;JavaScript;SQL;TypeScript;HTML;CSS;Bash/Shell,C#;JavaScript;SQL;TypeScript;HTML;CSS;Bash/Shell,"SQL Server;Microsoft Azure (Tables, CosmosDB, SQL, etc)","SQL Server;Microsoft Azure (Tables, CosmosDB, SQL, etc)",Azure,Azure,NaN,NaN,4.0,NaN,48000.0,NaN,NaN,NaN,NaN
2,2019-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","Data or business analyst;Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile;DevOps specialist;Engineer, data;Engineer, site reliability;Engineering manager;Senior executive/VP;System administrator",Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL;TypeScript,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust;SQL;TypeScript;WebAssembly,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Linux;MacOS;Microsoft Azure;Slack;Windows;WordPress,Android;AWS;Docker;IBM Cloud or Watson;Linux;Slack;Windows;WordPress,Yes,10 to 19 employees,8.0,I am not interested in new job opportunities,90000.0,40.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,2019-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;DevOps specialist",C#;JavaScript;SQL;TypeScript,C#;F#;SQL;TypeScript,Microsoft SQL Server;PostgreSQL;Redis;SQLite,Microsoft SQL Server;PostgreSQL;Redis;SQLite,AWS;Docker;Kubernetes;Linux;Microsoft Azure;Windows,AWS;Linux;Microsoft Azure;Windows,Yes,100 to 499 employees,23.0,"Iâ€™m not actively looking, but I am open to new opportunities",156000.0,50.0,NaN,NaN,NaN
9,2020-01-01,United States,Student,"Computer science, computer engineering, or software engineering",NaN,C;C#;C++;HTML/CSS;JavaScript;PHP;Python;SQL,C#;HTML/CSS;JavaScript;Python,MySQL;SQLite,MySQL,Android;iOS;Linux;Windows,Android;iOS;Linux;Windows,Yes,NaN,8.0,"Iâ€™m not actively looking, but I am open to new opportunities",NaN,NaN,NaN,NaN,Once a year
10,2018-01-01,United States,Employed full-time,Web development or web design,Back-end developer;Designer;Front-end developer;Full-stack developer;Marketing or sales professional;Mobile developer,Java;JavaScript;Objective-C;PHP;SQL;Swift;HTML;CSS;Bash/Shell,Assembly;C;C++;Java;JavaScript;PHP;Python;SQL;Swift;HTML;CSS,SQL Server;MySQL,SQL Server;MySQL;Oracle,Drupal;iOS;WordPress,iOS;Salesforce;SharePoint;WordPress,NaN,NaN,6.0,NaN,138000.0,NaN,NaN,NaN,NaN
10,2019-01-01,United States,Employed full-time,"Another engineering discipline (ex. civil, electrical, mechanical)",Engineering manager,Python,Python;VBA,Other(s):,Other(s):,NaN,NaN,Yes,"1,000 to 4,999 employees",35.0,"Iâ€™m not actively looking, but I am open to new opportunities",175000.0,45.0,NaN,NaN,NaN
10,2020-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","Developer, back-end;Developer, front-end;Developer, full-stack",C;C#;Java;SQL,C;C#;Java;SQL,Microsoft SQL Server,Microsoft SQL Server,Windows,Windows,No,500 to 999 employees,20.0,"Iâ€™m not actively looking, but I am open to new opportunities",106000.0,40.0,Better compensation;Wanting to work with new technologies;Growth or leadership opportunities,"Read company media, such as employee blogs or company culture videos;Company reviews from third party sites (e.g. Glassdoor, Blind);Publicly available financial information (e.g. Crunchbase)",Once a year

In [11]:
df.isnull().mean()

Year                      0.000000
Country                   0.000000
Employment                0.016042
UndergradMajor            0.114703
DevType                   0.096899
LanguageWorkedWith        0.082646
LanguageDesireNextYear    0.136365
DatabaseWorkedWith        0.227949
DatabaseDesireNextYear    0.332482
PlatformWorkedWith        0.176245
PlatformDesireNextYear    0.232292
Hobbyist                  0.385373
OrgSize                   0.507198
YearsCodePro              0.147614
JobSeek                   0.455476
ConvertedComp             0.178727
WorkWeekHrs               0.540604
NEWJobHunt                0.828009
NEWJobHuntResearch        0.832001
NEWLearn                  0.782158
dtype: float64

In [14]:
df.dtypes

Year                      datetime64[ns]
Country                           object
Employment                        object
UndergradMajor                    object
DevType                           object
LanguageWorkedWith                object
LanguageDesireNextYear            object
DatabaseWorkedWith                object
DatabaseDesireNextYear            object
PlatformWorkedWith                object
PlatformDesireNextYear            object
Hobbyist                          object
OrgSize                           object
YearsCodePro                     float64
JobSeek                           object
ConvertedComp                    float64
WorkWeekHrs                      float64
NEWJobHunt                        object
NEWJobHuntResearch                object
NEWLearn                          object
dtype: object

In [51]:
col_set = ['DevType', 'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith', 'PlatformDesireNextYear', 'NEWJobHunt', 'NEWJobHuntResearch']
for col in col_set:
    df[col] = df[col].fillna('null')
    df[col] = df[col].str.split(';', regex=True) 
    df[col] = df[col].map(set)

In [52]:
df.head()

,Year,Country,Employment,UndergradMajor,DevType,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,Hobbyist,OrgSize,YearsCodePro,JobSeek,ConvertedComp,WorkWeekHrs,NEWJobHunt,NEWJobHuntResearch,NEWLearn
RespondentID,,,,,,,,,,,,,,,,,,,,
1,2018-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","{Engineering manager, Full-stack developer}",{null},{null},{null},{null},{null},{null},NaN,NaN,NaN,NaN,141000.0,NaN,{null},{null},NaN
1,2019-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","{Developer, full-stack}","{Python, C, C#, SQL, C++}","{SQL, JavaScript, C#, C}","{MySQL, SQLite}","{MySQL, SQLite}","{Windows, Linux}","{Windows, Linux}",No,100 to 499 employees,1.0,I am not interested in new job opportunities,61000.0,80.0,{null},{null},NaN
1,2020-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering",{null},"{Ruby, SQL, HTML/CSS}","{Ruby, Java, Scala}","{MySQL, PostgreSQL, Redis, SQLite}","{MySQL, PostgreSQL}","{Windows, MacOS, Linux, AWS, Docker}","{Windows, Google Cloud Platform, Linux, Heroku, Docker}",Yes,NaN,8.0,NaN,NaN,NaN,{null},{null},Once a year
2,2018-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering",{Full-stack developer},"{HTML, C#, SQL, JavaScript, Bash/Shell, CSS, TypeScript}","{HTML, C#, SQL, JavaScript, Bash/Shell, CSS, TypeScript}","{SQL Server, Microsoft Azure (Tables, CosmosDB, SQL, etc)}","{SQL Server, Microsoft Azure (Tables, CosmosDB, SQL, etc)}",{Azure},{Azure},NaN,NaN,4.0,NaN,48000.0,NaN,{null},{null},NaN
2,2019-01-01,United States,Employed full-time,"Computer science, computer engineering, or software engineering","{Engineering manager, Data or business analyst, Developer, back-end, Senior executive/VP, Engineer, site reliability, Developer, mobile, Developer, desktop or enterprise applications, Developer, full-stack, Engineer, data, System administrator, DevOps specialist, Developer, front-end, Database administrator}","{HTML/CSS, Bash/Shell/PowerShell, PHP, SQL, JavaScript, TypeScript}","{HTML/CSS, Rust, Bash/Shell/PowerShell, WebAssembly, SQL, JavaScript, TypeScript}","{Firebase, MySQL, DynamoDB, Couchbase}","{MySQL, Redis, Firebase}","{Android, Windows, MacOS, WordPress, iOS, Microsoft Azure, Linux, Slack, AWS, IBM Cloud or Watson, Docker}","{Android, Windows, WordPress, Linux, Slack, AWS, IBM Cloud or Watson, Docker}",Yes,10 to 19 employees,8.0,I am not interested in new job opportunities,90000.0,40.0,{null},{null},NaN

In [56]:
set(df.JobSeek.unique())

{'I am actively looking for a job',
 'I am not interested in new job opportunities',
 'Iâ€™m not actively looking, but I am open to new opportunities',
 nan}

In [63]:
set_1 = {'null'}
for st in list(df.NEWJobHuntResearch):
    set_1.union(st)

In [70]:
set_1 = set().union(*list(df.NEWJobHuntResearch))
set_1

{'Company reviews from third party sites (e.g. Glassdoor, Blind)',
 'Directly asking current or past employees at the company',
 'Personal network - friends or family',
 'Publicly available financial information (e.g. Crunchbase)',
 'Read company media, such as employee blogs or company culture videos',
 'Read other media like news articles, founder profiles, etc. about the company',
 'null'}

In [75]:
pool = {}
col_jobhunt = ['NEWJobHunt', 'NEWJobHuntResearch']
col_pool = col_set + col_jobhunt
for col in col_pool:
    items_set = set().union(*list(df[col]))
    pool[col] = list(items_set)

In [78]:
dicts = {}
for col in col_pool:
    dicts[col] = { pool[col][i]:i for i in range(len(pool[col])) }